APP_CONFIGS = [['config', 'value'], 
                       ['home_directory', '.testdata'],
                       ['button_width', '40'],
                       ['button_height', '40']]
DATA = [['data_file_name', '(date,data_column_one,data_column_two,...)'], 
                ['marketing_messages', '(date,source,messages)'], 
                ['community_events', '(date,event_name,attendees)'],
                ['exp_nominations', '(date,nominations)'],
                ['exp_applications', '(date,applications)'], 
                ['exp_enrollment', '(date,enrollment)'],
                ['leap_nominations', '(date,nominations)'],
                ['leap_applications', '(date,applications)'],
                ['leap_enrollment', '(date,enrollment)'],
                ['lectures', '(date,title,calvert,charles,st_mary,satisfaction)'],
                ['surveys', '(date,surveys)'],
                ['fundraising', '(date,event,source,revenue)'], 
                ['lsmaa', '(date,enrollment,revenue)'], 
                ['program_sponsors', '(date,sponsor,number,level,revenue,notes)'], 
                ['lunch_sponsors', '(date,sponsor,session,pledged_paid,revenue,notes)'],
                ['event_sponsors', '(date,sponsor,event,revenue,notes)']]

GOALS = [['goal', 'percentage', '(sub_goal_zero,sub_goal_one,sub_goal_two,...)'],
         ['Value Proposition & Visibility', '.5', '(Marketing Messages,Community Events,EXP {year} Nominations,EXP {year} Applications,EXP {year} Enrollment,Leap {year} Nominations,Leap {year} Applications,Leap {year} Enrollment)'], 
         ['Community Engagement', '.5', "(LSM Lectures,Lecture Attendance,Calvert Attendance,Charles Attendance,St. Mary's Attendance,Satisfied-Very Satisfied,Interest Surveys)"], 
         ['Revenue', '.5', '(Fundraising Event Revenue,LSMAA Membership,LSMAA Revenue,Program Sponsors,LSM Lunch Sponsors,LSM Event Sponsors,Sponsorship Revenue)']]
SUB_GOALS = [['sub_goal', 'data_file', 'time', 'summed_column', 'committee', 'show_graph'],
             ['Marketing Messages', 'marketing_messages', 'monthly', 'messages', 'communications', 'True'],
             ['Community Events', 'community_events', 'monthly', 'rows', 'communications', 'True'],
             ['EXP {year} Nominations', 'exp_nominations', 'annual', 'nominations', 'recruiting', 'True'],
             ['EXP {year} Applications', 'exp_applications', 'annual', 'applications', 'recruiting', 'True'],
             ['EXP {year} Enrollment', 'exp_enrollment', 'annual', 'enrollment', 'recruiting', 'True'],
             ['Leap {year} Nominations', 'leap_nominations', 'annual', 'nominations', 'leap/recruiting', 'True'],
             ['Leap {year} Applications', 'leap_applications', 'annual', 'applications', 'leap/recruiting', 'True'],
             ['Leap {year} Enrollment', 'leap_enrollment', 'annual', 'enrollment', 'leap/recruiting', 'True'],
             ['LSM Lectures', 'lectures', 'annual', 'rows', 'alumni', 'False'],
             ['Lecture Attendance', 'lectures', 'annual', '(calvert,charles,st_mary)', 'alumni', 'False'],
             ['Calvert Attendance', 'lectures', 'annual', 'calvert', 'alumni', 'False'],
             ['Charles Attendance', 'lectures', 'annual', 'charles', 'alumni', 'False'],
             ["St. Mary's Attendance", 'lectures', 'annual', 'st_mary', 'alumni', 'False'],
             ['Satisfied-Very Satisfied', 'lectures', 'annual', 'satisfaction', 'alumni', 'False'],
             ['Interest Surveys', 'surveys', 'annual', 'surveys', 'alumni/program', 'False'],
             ['Fundraising Event Revenue', 'fundraising', 'annual', 'revenue', 'development', 'True'],
             ['LSMAA Membership', 'lsmaa', 'annual', 'enrollment', 'alumni', 'True'],
             ['LSMAA Revenue', 'lsmaa', 'annual', 'revenue', 'alumni', 'True'],
             ['Program Sponsors', 'program_sponsors', 'annual', 'rows', 'development', 'True'],
             ['LSM Lunch Sponsors', 'lunch_sponsors', 'annual', 'rows', 'program', 'True'],
             ['LSM Event Sponsors', 'event_sponsors', 'annual', 'rows', 'development', 'True'], 
             ['Sponsorship Revenue', '(program_sponsors,lunch_sponsors,event_sponsors)', 'annual', 'revenue', 'development', 'True']]
YEAR_CONFIGS = [['config', 'value'], 
                ['comp_year', 'None']]